apiVersion: apps/v1
kind: Deployment
metadata:
  name: appback
  labels:
    app: appback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appback
  template:
    metadata:
      labels:
        app: appback
    spec:
      containers:
        - name: appback
          image: bodukal/appback:v2
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 8081
          args:
            - "-javaagent:/jmx/jmx_prometheus_javaagent-0.20.0.jar=8081:/jmx/jmx_exporter_config.yaml"
          volumeMounts:
            - name: jmx-config
              mountPath: /jmx
      volumes:
        - name: jmx-config
          configMap:
            name: jmx-config

