apiVersion: v1
kind: Service
metadata:
  name: appback
  labels:
    app: appback
spec:
  selector:
    app: appback
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081

