# Chart.yaml
apiVersion: v2
name: appback
version: 0.1.0

---
# values.yaml
replicaCount: 1
image:
  repository: bodukal/appback
  tag: v2

---
# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appback
  labels:
    app: appback
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: appback
  template:
    metadata:
      labels:
        app: appback
    spec:
      containers:
        - name: appback
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 8081
          args:
            - "-javaagent:/jmx/jmx_prometheus_javaagent-0.20.0.jar=8081:/jmx/jmx_exporter_config.yaml"
          volumeMounts:
            - name: jmx-config
              mountPath: /jmx
      volumes:
        - name: jmx-config
          configMap:
            name: jmx-config

---
# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: appback
  labels:
    app: appback
spec:
  selector:
    app: appback
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081

---
# templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: appback-metrics
  labels:
    app: appback
    release: monitoring
spec:
  selector:
    matchLabels:
      app: appback
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics

---
# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jmx-config
  labels:
    app: appback
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
data:
  jmx_exporter_config.yaml: |
    startDelaySeconds: 0
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
      - pattern: '.*'

