replicaCount: 1

image:
  repository: bodukal/appback
  tag: v2
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: appback.puikusng.com
  ingressClassName: nginx

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
