apiVersion: v1
kind: ConfigMap
metadata:
  name: jmx-config
data:
  jmx_exporter_config.yaml: |
    startDelaySeconds: 0
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
      - pattern: '.*'

