grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.puikusng.com
    path: /
    pathType: Prefix
  adminPassword: "admin"  # or use a secure one + sealed secret

