apiVersion: apps/v1
kind: Deployment
metadata:
  name: appfront
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: appfront
  template:
    metadata:
      labels:
        app: appfront
    spec:
      containers:
        - name: appfront
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80

