server:
  service:
    type: ClusterIP          # No LoadBalancer; internal service
  ingress:
    enabled: true            # Enable ingress for ArgoCD
    hosts:
      - argocd.example.com   # Replace with your domain or host you want to use
    tls:
      - hosts:
          - argocd.example.com
        secretName: argocd-tls-cert  # Optional TLS secret if you want HTTPS

