replicaCount: 1

image:
  repository: bodukal/appfront
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: appfront.puikusng.com
  ingressClassName: nginx 

resources: {}

